services:
  xadmin-client-build:
    container_name: xadmin-client-build
    image: "xadmin-client-build"
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile.build
    command:
      - sh
      - -c
      - pnpm install --frozen-lockfile && pnpm build

  xadmin-client-prod:
    container_name: xadmin-client-prod
    restart: always
    image: "nginx:stable-alpine"
    volumes:
      - ./dist:/usr/share/nginx/html
    command: [ "nginx", "-g", "daemon off;" ]
    #depends_on:
    #   - xadmin-client-build
    ports:
      - 8891:80
